


export default {
  async fetch(request) {
    const { method, url } = request;
    const { pathname } = new URL(url);



	  // Dados simulados (substitua por sua lógica real)
	    const livros = [
       {
     id : 1,
    titulo: "A Princesa que Salvava Príncipes",
    autor: "Claudia Souza",
    editora: "Callis",
    tema: "empoderamento feminino",
    genero: "Fantasia",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Neste conto de fadas moderno, a princesa não é uma jovem fraca que desmaia diante do dragão. Contrariando todas as expectativas, ela invade o quarto da bruxa e enfrenta quadros com bocas e olhos de verdade, tudo para resgatar o príncipe.",
    dataPublicacao: "2012-01-01",
    dataCatalogo: "2025-05-18",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
  {
    id: 2,
    titulo: "A Ginga da Rainha",
    autor: "Iris Maria da Costa Amâncio",
    editora: "Mazza Edições",
    tema: "empoderamento feminino",
    genero: "Educativo",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 40,
    resumo: "A história da rainha Nzinga, uma das mulheres mais importantes da história africana, que lutou contra a escravidão e a colonização em Angola. Um livro que valoriza a cultura afro-brasileira e a resistência feminina.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-05-25",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 3,
    titulo: "O Menino Azul",
    autor: "Cecília Meireles, Lúcia Hiratsuka",
    editora: "Global Editora",
    tema: "questões sociais",
    genero: "Poesia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Um poema clássico de Cecília Meireles, ilustrado por Lúcia Hiratsuka, que fala sobre o desejo de uma criança por um burrinho para viver aventuras e alimentar sua imaginação.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-05-25",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },

{
  id: 4,
  titulo: "ABC da Capoeira",
  autor: "Victor Alvim I. Garcia",
  editora: "Victor Alvim",
  tema: "capoeira",
  genero: "Educativo",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 48,
  resumo: "Este livro apresenta de forma educativa e acessível os fundamentos da capoeira, suas origens, movimentos e importância cultural. Voltado para o público jovem, busca ensinar valores históricos e sociais por meio da prática dessa arte afro-brasileira.",
  dataPublicacao: "2006-01-01",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
{
  id: 5,
  titulo: "África; conto do rio, da selva e da savana",
  autor: "Silvana Salerno",
  editora: "Girassol",
  tema: "questões sociais",
  genero: "Contos",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 56,
  resumo: "Reunindo histórias passadas de geração em geração no continente africano, o livro convida o leitor a mergulhar em contos que se desenrolam às margens dos rios, nas florestas densas e nas vastas savanas. Uma celebração da oralidade e da diversidade cultural da África.",
  dataPublicacao: "2009-01-01",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

{
  id: 6,
  titulo: "A África que você fala",
  autor: "Claudio Fragata",
  editora: "Globinho",
  tema: "questões sociais",
  genero: "Educativo",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 32,
  resumo: "Apresenta de forma leve e ilustrada palavras de origem africana incorporadas ao português, explicando suas raízes em quimbundo, iorubá, jeje e banto.",
  dataPublicacao: "15-01-2021",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
{
  id: 7,
  titulo: "África recontada para crianças",
  autor: "Avani Souza Silva",
  editora: "Martin Claret",
  tema: "questões sociais",
  genero: "Contos",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 64,
  resumo: "Reconta lendas e histórias do continente africano em formato acessível para crianças, valorizando a oralidade e a diversidade cultural.",
  dataPublicacao: "2019-01-01",
  dataCatalogo: "2025-06-13",
 capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

{
  id: 8,
  titulo: "Aqui no morro, tem princesa sim!",
  autor: "Simone Botelho",
  editora: "Albatrozinho",
  tema: "empoderamento feminino",
  genero: "Poesia",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 40,
  resumo: "Uma princesa que vive no morro e quebra estereótipos tradicionais de fadas: real, forte, periférica e protagonista de sua própria história.",
  dataPublicacao: "2020-01-01",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

{
  id: 8,
  titulo: "Amoras",
  autor: "Emicida",
  editora: "Companhia das Letrinhas",
  tema: "questões sociais",
  genero: "Poesia",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 44,
  resumo: "Inspirado na música 'Amoras', o livro celebra a autoestima e o orgulho racial desde a infância, por meio de texto poético e ilustrações suaves.",
  dataPublicacao: "14-09-2018",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

{
  id: 9,
  titulo: "Amor de cabelo",
  autor: "Matthew A. Cherry",
  editora: "Galerinha",
  tema: "questões sociais",
  genero: "conto",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 32,
  resumo: "Baseado no curta vencedor do Oscar “Hair Love”, o livro narra o carinho entre pai e filha enquanto eles encontram o penteado perfeito para celebrar um momento especial, valorizando o cabelo crespo e o amor familiar.",
  dataPublicacao: "04-05-2020",
  dataCatalogo: "2025-06-13",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
{
  id: 10,
  titulo: "Batismo da Capoeirinha (confusão no Quintal)",
  autor: "Sérgio Ballouk",
  editora: "Quilombhoje",
  tema: "capoeira",
  genero: "Cultura",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 48,
  resumo: "A pequena capoeirinha vive uma divertida confusão no quintal durante seu batizado simbólico como capoeirista, entre rodas improvisadas, batuques e a comunidade que a acompanha.",
  dataPublicacao: "2018-01-01",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
{
  id: 11,
  titulo: "Beata; a menina das águas",
  autor: "Elaine Marcelina",
  editora: "Malê mirim",
  tema: "axé",
  genero: "Biografia",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 24,
  resumo: "Baseado na infância de Mãe Beata de Iemanjá, a obra mostra a ligação espiritual da menina com a natureza, celebrando sua vocação e legado de resistência religiosa :contentReference[oaicite:1]{index=1}.",
  dataPublicacao: "17-04-2021",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
{
  id: 12,
  titulo: "Betina",
  autor: "Nilma Lino Gomes",
  editora: "Maza Edições",
  tema: "questões sociais",
  genero: "Reflexão",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 32,
  resumo: "Através da personagem Betina, o livro promove reflexão sobre a autoestima e a identidade negra desde a infância, com linguagem acessível e imagens evocativas.",
  dataPublicacao: "2022-01-01",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
{
  id: 13,
  titulo: "Bolota; uma certa jabuticaba muito esperta",
  autor: "Iray Galrão",
  editora: "Escritinha",
  tema: "questões sociais",
  genero: "Conto",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 40,
  resumo: "A história acompanha Bolota, uma jabuticaba curiosa e destemida, em aventuras pela mata, ensinando sobre amizade, ecologia e o ciclo da vida de forma divertida.",
  dataPublicacao: "2021-01-01",
  dataCatalogo: "2025-06-13",
 capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
{
  id: 14,
  titulo: "Brincar na rua",
  autor: "Magna Domingues",
  editora: "Baú Encantado",
  tema: "questões sociais",
  genero: "Poesia",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 36,
  resumo: "Uma celebração poética da infância, do brincar na rua e da inventividade das crianças que transformam a rua em palco de suas histórias cotidianas e sonhos.",
  dataPublicacao: "2020-01-01",
  dataCatalogo: "2025-06-13",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

{
   id: 15,
  titulo:   "Bruna e a Galinha d’Angola",
  autor: "Gercilga de Almeida",
  editora: "EDC e Pallas",
  tema: "questões sociais",
  genero: "Literatura",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 24,
  resumo: "Primeiro livro infantil a retratar o universo mítico africano, contando de forma lúdica e didática como a galinha-d’angola participou da criação do mundo, a partir da curiosidade de Bruna e das narrativas de sua avó travessa.",
  dataPublicacao:"19-03-2009",
  capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

 {
        id: 16,
        titulo: "Bucala; a pequena princesa do Quilombo Cabula",
        autor: "Davi Nunes",
        editora: "Malê Mirim",
        tema: "questões sociais",
        genero: "Aventura",
        classificacaoLiteraria: "Infantojuvenil",
        numeroPaginas: 32,
        resumo: "Bucala é uma princesa quilombola que vive no Quilombo do Cabula no século XIX...",
        dataPublicacao: "2019-01-01",
        dataCatalogo: "2025-06-13",
         capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },

 {
    id: 17,
    titulo: "Calu; uma menina cheia de histórias",
    autor: "Cássia Valle",
    ilustrador: "Maria Chantal",
    editora: "Malê Mirim",
    tema: "questões sociais",
    genero: "Ficção",
    classificacao: "Infantojuvenil",
    paginas: 32,
    resumo: "A protagonista Calu transforma seu bairro em um 'museu a céu aberto', celebrando a cultura local e fortalecendo o sentimento de pertencimento e preservação do patrimônio imaterial.",
    data_publicacao: "2017-01-02",
    data_catalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
  {
    id: 18,
    titulo: "Chuva de manga",
    autor: "James Rumford",
    editora: "Brinque-Book",
    tema: "questões sociais",
    genero: "Literatura",
    classificacao: "Infantojuvenil",
    paginas: 32,
    resumo: "No Chade, o menino Tomás celebra as chuvas que o tornam fértil, colhendo mangas e construindo um carrinho de lata. Uma narrativa que constrói empatia cultural e convida à reflexão sobre valores simples e universais.",
    data_publicacao: "2005-11-04",
    data_catalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
{
  id: 19,
    titulo: "Com qual penteado eu vou?",
    autor: "Kiusam de Oliveira",
    ilustrador: "Rodrigo Andrade",
    editora: "Melhoramentos",
    tema: "questões sociais",
    genero: "Conto",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 48,
    resumo: "Durante a festa de 100 anos do bisavô Seu Benedito, as bisnetas escolhem penteados especiais e presenteiam o centenário com as virtudes que mais admiram, celebrando ancestralidade, família, negritude e representatividade capilar.",
    dataPublicacao: "2021-06-04",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
  {
    id: 20,
    titulo: "Contos de Monadenge",
    autor: "Israel Neto e Jader Oliveira",
    ilustrador: "Soberana Ziza",
    editora: "Literatura suburbana e literária besouro",
    tema: "questões sociais",
    genero: "Contos",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Monadenge, contador de histórias do quilombo de Alquatune, narra dois contos fantásticos às crianças, conectando passado africano e legado quilombola em um resgate poético das raízes.",
    dataPublicacao: "2023-01-01", // geralmente volumes da coleção são recentes ,
    dataCatalogo: "2025-06-17",
 capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 21,
    titulo: "De grão em grão, o sucesso vem na mão",
    autor: "Katie Smith Milway",
    ilustrador: "Eugenie Fernandes",
    editora: "Melhoramentos",
    tema: "questões sociais",
    genero: "Biografia",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Inspirado em fatos reais, conta a trajetória de Kojo, menino que ajuda a mãe vendendo ovos, volta à escola, obtém empréstimos e constrói uma granja — um poderoso relato sobre resiliência e futuro.",
    dataPublicacao: "2008-11-08",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },

  {
    id: 22,
    titulo: "Dengos na moringa de voinha",
    autor: "Ana Fátima",
    ilustrador: "Fernanda Rodrigues",
    editora: "Brinque‑Book",
    tema: "questões sociais",
    genero: "Conto",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "A história aproxima o leitor dos pequenos gestos do cotidiano familiar — carinhos, cheiros, danças — contados pela moringa de Voinha, objeto que simboliza a ancestralidade e os afetos herdados da família quilombola em uma crônica poética e delicada.",
    dataPublicacao: "2023-06-27",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 23,
    titulo: "De passinho em passinho",
    autor: "Otávio Júnior",
    ilustrador: "Bruna Lubambo",
    editora: "Companhia das Letrinhas",
    tema: "questões sociais",
    genero: "Prosa / poema ",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Livro que celebra o passinho — dança urbana carioca com influências do funk, capoeira, samba e frevo —, retratando sonhos, movimento e representatividade, com texto poético e ilustrações vibrantes.",
    dataPublicacao: "2021-07-13",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 24,
    titulo: "Descobertas de Kito",
    autor: "Douglas Coelho",
    editora: "Letraria",
    tema: "questões sociais",
    genero: "Didático",
    classificacaoLiteraria: "Infatil",  // faltam dados online, estimado
    numeroPaginas: 40,                 // estimado
    resumo: "Kito, uma criança curiosa, explora o mundo ao seu redor, levantando perguntas sobre plantas, animais e fenômenos, de forma lúdica e incentivando o pensamento crítico e científico desde cedo.",
    dataPublicacao: "2022-01-01",      // estimado,
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 25,
    titulo: "ÉDÁ, EDÁ - as palavras e cores da criação Òkè",
    autor: "Mariana Moretti e Luiz Carlos Garcia",
    ilustrador: "Mariana Moretti",
    editora: "Literatura suburbana e literária besouro",
    tema: "questões sociais",
    genero: "Literatura",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "Inspirado nas narrativas iorubás sobre a criação do mundo, o livro apresenta a cosmogonia Òkè através de imagens coloridas e linguagem poética. Um convite à imaginação e à valorização das raízes africanas.",
    dataPublicacao: "2023-10-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 26,
    titulo: "Eu, curiosa?",
    autor: "Flavia da Cruz e Cátia Luciana Pereira",
    ilustrador: "Júlia Lima",
    editora: "Literatura suburbana e literária besouro",
    tema: "questões sociais",
    genero: " Narrativa / Poema",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Uma menina negra cheia de perguntas embarca em descobertas sobre si mesma, sobre a vida e sobre o mundo. O livro propõe uma valorização da infância negra através da curiosidade e imaginação.",
    dataPublicacao: "2023-07-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 27,
    titulo: "Era dos Erês; uma era ao culto da natureza e dos orixás",
    autor: "Adriano Bitarães Netto",
    ilustrador: "Mariana Barcelos",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Didático",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 40,
    resumo: "A obra apresenta os Erês, entidades infantis da mitologia afro-brasileira, e sua relação com os orixás e a natureza. Um livro que resgata saberes sagrados com linguagem acessível e ilustrações simbólicas.",
    dataPublicacao: "2021-11-15",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

    {
    id: 28,
    titulo: "Férias fantásticas de Lili",
    autor: "Lívia Natália",
    ilustrador: "Carolina Teixeira",
    editora: "Ciclo Contínuo",
    tema: "axé",
    genero: "Poesia ",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 48,
    resumo: "Lili revive suas férias na Bahia, entre lagoas, praia e memórias de encantamentos da infância, vivenciados à beira do Abaeté e cheios de magia e religiosidade ligada aos Orixás.",
    dataPublicacao: "2018-09-30",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 29,
    titulo: "Foi assim que eu e a escuridão ficamos amigas",
    autor: "Emicida",
    ilustrador: "Aldo Fabrini",
    editora: "Companhia das Letrinhas",
    tema: "questões sociais",
    genero: "Poesia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "Duas meninas‑personificações do dia e da noite se conhecem e descobrem que, apesar dos medos iniciais, podem se tornar amigas, em narrativa poética que trata ansiedade e empoderamento emocional.",
    dataPublicacao: "2020-10-05",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 30,
    titulo: "Gabriela; a princesa do Daomé",
    autor: "Marta Rodrigues",
    ilustrador: "Não informado",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Biografia",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32, // estimado
    resumo: "Gabriela é retratada como jovem princesa do antigo reino do Daomé, em território da atual Benim, seu percurso inspira reflexão sobre o poder feminino e a história africana.",
    dataPublicacao: "2022-01-01", // estimado,
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },

   {
    id: 32,
    titulo: "Gosto de África: história de lá e daqui",
    autor: "Joel Rufino dos Santos",
    ilustrador: "Pedro Rafael",
    editora: "Global",
    tema: "questões sociais",
    genero: " Conto ",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "O livro apresenta histórias que aproximam as culturas africana e afro-brasileira, celebrando suas raízes e influências no cotidiano e na história do Brasil.",
    dataPublicacao: "2007-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
  {
    id: 33,
    titulo: "Histórias Africanas para contar e recontar",
    autor: "Rogério Andrade Barbosa",
    ilustrador: "Martinho de Haro",
    editora: "Editora do Brasil",
    tema: "questões sociais",
    genero: "Conto",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Coletânea de contos africanos, com lições de vida, valores e tradições, pensada para preservar a sabedoria dos griôs e incentivar a oralidade nas crianças.",
    dataPublicacao: "2003-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 34,
    titulo: "Histórias do tio Jimbo",
    autor: "Nei Lopes",
    ilustrador: "Não informado",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Conto / Narrativa",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 40,
    resumo: "O Tio Jimbo, griô africano, narra contos divertidos e educativos sobre a vida, os valores e os deuses africanos, promovendo uma imersão cultural.",
    dataPublicacao: "2007-01-01", // estimado,
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 35,
    titulo: "Ifá, o Adivinho",
    autor: "Reginaldo Prandi",
    ilustrador: "Pedro Rafael",
    editora: "Companhia das Letrinhas",
    tema: "questões sociais",
    genero: "Conto",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Baseado no sistema de adivinhação Ifá, o livro apresenta contos que explicam a sabedoria do oráculo africano e o papel dos Orixás na orientação das pessoas.",
    dataPublicacao: "2004-08-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 36,
    titulo: "Igbo e as princesas",
    autor: "Marcos Cajé",
    ilustrador: "Não informado",
    editora: "Marcos Cajé",
    tema: "questões sociais",
    genero: "aventura",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 28,
    resumo: "Através da jornada de Igbo e das princesas, o autor apresenta elementos mitológicos africanos e valores como solidariedade, honra e ancestralidade.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 37,
    titulo: "Jongo",
    autor: "Sonia Rosa",
    ilustrador: "Mauricio Negro",
    editora: "Pallas",
    tema: "questões sociais",
    genero: "Infantil / História",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "O livro apresenta o Jongo, dança de origem africana trazida por negros escravizados, mostrando sua musicalidade, oralidade e importância cultural no Brasil.",
    dataPublicacao: "2007-06-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },

   {
    id: 38,
    titulo: "Nós de Axé",
    autor: "Janaína de Figueiredo",
    editora: "Aletria",
    tema: "axé",
    genero: "Infantil / Religioso",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "História sensível que introduz elementos do Candomblé e da ancestralidade com respeito e afeto para crianças.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
  {
    id: 39,
    titulo: "Nove pentes d'África",
    autor: "Cidinha da Silva",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Infantil / Fantasia",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 44,
    resumo: "Garota viaja por nove reinos africanos em busca de pentes mágicos, aprendendo sobre história, autoestima e empoderamento.",
    dataPublicacao: "2019-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 40,
    titulo: "Obax",
    autor: "André Neves",
    editora: "Brinque-book",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Obax é uma menina cheia de sonhos que transforma sua aldeia com a força de sua imaginação e conexão com a natureza.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

    {
    id: 41,
    titulo: "Koumba e o Tambor Diambê",
    autor: "Madu Costa",
    ilustrador: "Não informado",
    editora: "Pallas",
    tema: "questões sociais",
    genero: "Infantil / Conto",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Koumba é um jovem africano que herda o tambor mágico de seu avô. A história valoriza a ancestralidade e o poder da música como elo cultural.",
    dataPublicacao: "2011-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 42,
    titulo: "Lenço de cetim da mamãe",
    autor: "Chimamanda Ngozi Adichie / Nwa Grace-James",
    ilustrador: "Joelle Avelino",
    editora: "Companhia das Letrinhas",
    tema: "familias diversas",
    genero: "Infantil / Narrativa contemporânea",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Baseado em conto de Chimamanda, o livro retrata a relação de uma criança com sua mãe e os símbolos culturais herdados, como o lenço de cetim.",
    dataPublicacao: "2022-05-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 43,
    titulo: "Lendas de Dandara",
    autor: "Jarid Arraes",
    ilustrador: "Não informado",
    editora: "Cultura",
    tema: "questões sociais",
    genero: "Infantil / Biográfico-ficcional",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 48,
    resumo: "Reconta lendas inspiradas na guerreira Dandara dos Palmares, abordando temas de luta, liberdade e protagonismo feminino negro.",
    dataPublicacao: "2015-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 44,
    titulo: "Letras de Carvão",
    autor: "Irene Vasco e Juan Palomino",
    ilustrador: "Juan Palomino",
    editora: "Pulo do Gato",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Menina da zona rural aprende a ler e escrever, superando obstáculos. Homenagem à educação e à força das comunidades marginalizadas.",
    dataPublicacao: "2016-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 45,
    titulo: "Luz de Aisha",
    autor: "Aza Njeri e Luana Rodrigues",
    ilustrador: "Não informado",
    editora: "Rebuliço",
    tema: "axé",
    genero: "Infantil / Religioso-cultural",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 36,
    resumo: "Aisha vive uma jornada de descoberta sobre sua herança iorubá e a presença dos Orixás em sua vida cotidiana.",
    dataPublicacao: "2023-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 46,
    titulo: "Makeba vai à Escola",
    autor: "Ana Fátima",
    ilustrador: "Não informado",
    editora: "Cogito",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Makeba é uma menina negra que enfrenta o primeiro dia de aula lidando com sua identidade, cabelo e aceitação, com leveza e representatividade.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 47,
    titulo: "Makori; a pequena princesa",
    autor: "Marcos Cajé",
    ilustrador: "Não informado",
    editora: "Ereginga Educação",
    tema: "questões sociais",
    genero: "Infantil / Conto de fadas africano",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 30,
    resumo: "Makori é uma jovem princesa africana que aprende sobre valores e ancestralidade através de aventuras com animais sagrados.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 48,
    titulo: "Mandisa e a vovó Alegria",
    autor: "Vagner Amaro",
    ilustrador: "Não informado",
    editora: "Malê Mirim",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 28,
    resumo: "Mandisa aprende com sua avó sobre as histórias de seu povo, costumes africanos e valores como afeto, respeito e autoestima.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 49,
    titulo: "Mar de Manu",
    autor: "Cidinha da Silva",
    ilustrador: "Não informado",
    editora: "Kuanza Produções",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Manu navega por mares simbólicos que representam suas emoções e sua ancestralidade, em um texto lírico e sensível.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 50,
    titulo: "Meninas negras",
    autor: "Madu Costa",
    ilustrador: "Não informado",
    editora: "Mazza",
    tema: "questões sociais",
    genero: "Infantil / Poesia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Uma homenagem poética à força, beleza e diversidade das meninas negras, com ilustrações vibrantes e mensagens de autoestima.",
    dataPublicacao: "2018-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 51,
    titulo: "Menina Nicinha",
    autor: "Evelyn Sacramento",
    ilustrador: "Não informado",
    editora: "Lendo Mulheres Negras / Aldir Blanc Bahia",
    tema: "familias diversas",
    genero: "Infantil",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 36,
    resumo: "Nicinha vive uma história sensível sobre identidade, convivência familiar e descobertas no contexto de sua cultura local afro-baiana.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },

  {
    id: 52,
    titulo: "Menino voador e o aprendiz de vagalume",
    autor: "Jota Revella e Regina Alonso",
    editora: "Literatura Suburbana e Literária Besouro",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 36,
    resumo: "Um menino e seu avô compartilham sonhos e histórias que iluminam a infância em meio à realidade da periferia.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 53,
    titulo: "Menino coração de tambor",
    autor: "Nilma Lino Gomes",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Narrativa sobre um menino que encontra no tambor um elo com suas raízes, fortalecendo sua autoestima e cultura.",
    dataPublicacao: "2007-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 54,
    titulo: "Minha dança tem história",
    autor: "Bell Hooks e Chris Raschka",
    editora: "Boi ta tá",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Poema de bell hooks traduzido com imagens expressivas, reforçando orgulho do corpo negro e suas expressões culturais.",
    dataPublicacao: "2018-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 55,
    titulo: "Minha mãe é negra sim!",
    autor: "Patrícia Santana",
    editora: "Maza Edições",
    tema: "familias diversas",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Menina aprende a reconhecer a beleza e força de sua mãe negra em uma história afetuosa sobre orgulho racial.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 56,
    titulo: "Meu crespo é de rainha",
    autor: "Bell Hooks",
    editora: "Boi ta tá",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Poema de empoderamento que celebra os cabelos crespos e sua beleza única, com ilustrações vibrantes.",
    dataPublicacao: "2018-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 57,
    titulo: "Neguinha sim!",
    autor: "Renato Gama",
    editora: "Sá Menina",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Uma menina negra encontra força para se afirmar e se orgulhar de quem é, enfrentando o racismo com poesia.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 58,
    titulo: "Neta de Anita",
    autor: "Anderson de Oliveira",
    editora: "Maza Edições",
    tema: "familias diversas",
    genero: "Infantil / Histórico",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Garota herda a força de sua ancestral, Anita Garibaldi, e inspira coragem nas novas gerações.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 59,
    titulo: "Nikkê",
    autor: "Édimo de Almeida Pereira",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Nikkê descobre a importância de seu nome e da sua origem, mergulhando nas histórias e símbolos da cultura afro-brasileira.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

    {
    id: 68,
    titulo: "Pequena porta estandarte",
    autor: "Daniel Renard",
    editora: "Seed",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 30,
    resumo: "Uma menina sonha em ser porta-estandarte em um desfile de carnaval, revivendo tradições culturais com beleza e esperança.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 69,
    titulo: "Pênalti",
    autor: "Geni Guimarães",
    editora: "Malê Mirim",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 34,
    resumo: "História de um menino negro apaixonado por futebol que enfrenta obstáculos sociais e raciais em busca de seus sonhos.",
    dataPublicacao: "2015-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 60,
    titulo: "Pequeno príncipe preto",
    autor: "Rodrigo França",
    editora: "Nova Fronteira",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Inspirado em 'O Pequeno Príncipe', esta obra reconstrói o protagonismo de um menino negro em um universo afetivo e poético.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
 
    {
    id: 61,
    titulo: "Omo-Obá: histórias de princesas",
    autor: "Kiusam de Oliveira",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Infantil / Contos",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Histórias de princesas africanas inspiradas nos orixás femininos, reforçando o empoderamento de meninas negras.",
    dataPublicacao: "2009-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 62,
    titulo: "Omo: o rio da liberdade",
    autor: "Vanessa Alexandre",
    editora: "PAE",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Poema que narra o encontro de uma criança com o rio Omo, símbolo de força, liberdade e ancestralidade africana.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 65,
    titulo: "O ônibus de Rosa",
    autor: "Fabrizio Silim",
    editora: "SM",
    tema: "questões sociais",
    genero: "Infantil / Histórico",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Baseado na história de Rosa Parks, este livro inspira coragem e resistência contra o racismo desde a infância.",
    dataPublicacao: "2008-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 66,
    titulo: "Oranyam e a grande pescaria",
    autor: "Dayse Cabral de Moura",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "Oranyam aprende com seu avô sobre valores ancestrais e a relação com o mar e os ciclos da vida.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 67,
    titulo: "Panela de barro e colher de pau; broa de milho, berimbau e carnaval",
    autor: "Nará Souza Oliveira",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 38,
    resumo: "Livro poético que celebra os utensílios, comidas e sons da cultura negra com ritmo, sabor e memória.",
    dataPublicacao: "2019-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },

    {
    id: 68,
    titulo: "Quem contou foi Camará",
    autor: "Vários autores",
    editora: "Bejiró",
    tema: "questões sociais",
    genero: "Contos / Narrativas tradicionais",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 52,
    resumo: "Coletânea de histórias inspiradas na tradição oral africana, com o griot Camará como narrador.",
    dataPublicacao: "2016-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 69,
    titulo: "Ruas do brincar",
    autor: "Leandro Rodrigues e Fernando Erminio",
    editora: "Coleção Literária Besouro",
    tema: "questões sociais",
    genero: "Fotolivro / Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 48,
    resumo: "Registro fotográfico e poético das brincadeiras tradicionais de rua com forte influência afro-brasileira.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 70,
    titulo: "Semente que veio da África",
    autor: "Heloísa Pires Lima, Georges Gneka e Mário Lemos",
    editora: "Salamandra",
    tema: "questões sociais",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 44,
    resumo: "Explica a influência da África no Brasil a partir da história de uma semente, símbolo da cultura viva.",
    dataPublicacao: "2007-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },

  {
    id: 71,
    titulo: "Pequenos contos negros",
    autor: "Blaise Cendrars",
    editora: "SM",
    tema: "questões sociais",
    genero: "Contos",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 64,
    resumo: "Antologia com histórias inspiradas em narrativas africanas e afrodescendentes, com reflexões sobre identidade e cultura.",
    dataPublicacao: "2012-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
  {
    id: 72,
    titulo: "Pretinha de neve e os sete gigantes",
    autor: "Rubem Filho",
    editora: "Paulinas",
    tema: "questões sociais",
    genero: "Conto / Releitura",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Releitura afrocentrada do clássico 'Branca de Neve', com protagonismo negro e elementos culturais brasileiros.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 73,
    titulo: "Princesa e o vento",
    autor: "Martha Rodrigues",
    editora: "Maza Edições",
    tema: "questões sociais",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "A história de uma princesa que escuta a sabedoria do vento e mergulha em uma viagem ancestral.",
    dataPublicacao: "2018-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
  {
    id: 74,
    titulo: "Princesas negras",
    autor: "Ariane Celestino Meireles",
    editora: "Malê Mirim",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Livro ilustrado que valoriza a beleza e a diversidade das meninas negras, mostrando que todas podem ser princesas.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 75,
    titulo: "Quanta África tem no dia de alguém?",
    autor: "Renata Fernandes",
    editora: "Ciranda na Escola",
    tema: "questões sociais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Mostra como a cultura africana está presente no cotidiano das crianças, mesmo que elas nem percebam.",
    dataPublicacao: "2021-08-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },

    {
    id: 76,
    titulo: "Sonia Rosa; Tabuleiro da Baiana",
    autor: "Sonia Rosa",
    editora: "Pallas",
    tema: "questões sociais",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Explora o universo das baianas do acarajé e suas tradições, com foco no respeito à cultura de matriz africana.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 77,
    titulo: "Sonia Rosa; Jongo",
    autor: "Sonia Rosa",
    editora: "Pallas",
    tema: "questões sociais",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Apresenta o jongo, dança de origem africana presente na cultura popular brasileira, de forma acessível às crianças.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
  },
  {
    id: 78,
    titulo: "Sulwe",
    autor: "Lupita Nyong'o",
    editora: "Rocco Pequenos Leitores",
    tema: "questões sociais",
    genero: "Livro ilustrado / Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 48,
    resumo: "Sulwe é uma menina com a pele da cor da meia-noite que embarca em uma jornada para descobrir sua beleza interior.",
    dataPublicacao: "2020-03-01",
    dataCatalogo: "2025-06-17",
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},

 {
    id: 79,
    titulo: "Sonia Rosa; Capoeira",
    autor: "Sonia Rosa",
    editora: "Pallas",
    tema: "capoeira",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Livro introdutório sobre a capoeira, com linguagem acessível e ilustrações que retratam a importância dessa manifestação cultural.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 80,
    titulo: "Sonia Rosa; Maracatu",
    autor: "Sonia Rosa",
    editora: "Pallas",
    tema: "questões sociais",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Apresenta a história do maracatu e sua importância como expressão cultural afro-brasileira, em linguagem lúdica.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },

   {
    id: 81,
    titulo: "Tunde e as aves misteriosas",
    autor: "Ana Fátima",
    editora: "Ereginga Educação",
    tema: "questões sociais",
    genero: "Infantil / Fantasia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Tunde é um menino curioso que embarca numa jornada mágica para salvar aves encantadas e redescobrir tradições ancestrais.",
    dataPublicacao: "2020-09-01",
    dataCatalogo: "2025-06-17",
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
  {
    id: 82,
    titulo: "Xangô, o trovão",
    autor: "Reginaldo Prandi",
    editora: "Companhia das Letrinhas",
    tema: "questões sociais",
    genero: "Infantil / Mitologia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 48,
    resumo: "Um retrato encantador de Xangô, o orixá do trovão e da justiça, apresentado com linguagem acessível e rica em elementos simbólicos.",
    dataPublicacao: "2001-08-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
 },
  {
    id: 83,
    titulo: "Zula, a Guerreira",
    autor: "Marcos Cajé",
    editora: "Crianças Diversas",
    tema: "empoderamento feminino",
    genero: "Infantil / Ação / Identidade",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "Zula é uma heroína determinada a mudar o mundo com coragem, representando o poder das meninas negras em suas lutas e sonhos.",
    dataPublicacao: "2023-04-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"
},
    {
    id: 84,
    titulo: "Super negro",
    autor: "Caio do Cordel",
    editora: "Caio do Cordel",
    tema: "questões sociais",
    genero: "Infantil / Aventura",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Uma narrativa inspiradora sobre um menino negro que descobre seu valor e poderes ao enfrentar desafios cotidianos como um verdadeiro herói.",
    dataPublicacao: "2021-06-01",
    dataCatalogo: "2025-06-17",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",},
 
{
  id: 85,
  titulo: "Conceição Evaristo",
  autor: "Orlando Nilha",
  editora: "Editora Mostarda",
  tema: "Empoderamento Feminino",
  genero: "Biografia infantil/juvenil",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 32,
  resumo: "Biografia ilustrada da escritora Conceição Evaristo, destacando sua trajetória desde a favela Pendura Saia até se tornar professora, doutora em Literatura e uma das maiores vozes negras do Brasil.",
  dataPublicacao: "08 de fevereiro de 2021",
  colecao: "Black Power",
  dataCatalogo: "", 
   capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Conceicao.jpe?raw=true",
  mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Conceicao.jpeg?raw=true"},

 {
    id: 86,
    titulo: "Black Power Abdias do Nascimento",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Negro",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

    
  },
  {
    id: 87,
    titulo: "Black Power Aleijadinho – Antonio Francisco Lisboa",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Negro",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

  },
  {
    id: 88,
    titulo: "Black Power Angela Davis",
    autor: "Gabriela Bauerfeldt",
    editora: "Mostarda",
    tema: "Empoderamento Feminino ",
    genero: "Não ficção infantil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: "9786588183069",
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

  },
  {
    id: 89,
    titulo: "Black Power Barack Obama",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Negro",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

  },
  {
    id: 90,
    titulo: "Black Power Beatriz Nascimento",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Feminino ",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

  },
  {
    id: 91,
    titulo: "Carolina Maria de Jesus",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Feminino",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Carolina.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Carolina.jpg?raw=true",
    isbn: null
  },
  {
    id: 92,
    titulo: "Black Power Conceição Evaristo",
    autor: "Orlando Nilha",
    editora: "Mostarda",
    tema: "Empoderamento Feminino",
    genero: "Biografia juvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: "9786588183038",
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

  },
  {
    id: 93,
    titulo: "Black Power Dandara e Zumbi",
    autor: "Maria Julia Maltese",
    editora: "Mostarda",
    tema: "Empoderamento Negro",
    genero: "Biografia juvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: "9786588183021",
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

  },
  {
    id: 94,
    titulo: "Black Power Glória Maria Matta da Silva – Edição Especial – Capa Dura",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Feminino e Negro",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

  },
  {
    id: 95,
    titulo: "Black Power Hamilton Naki",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Negro",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/APrincesaQueSalvaPrincipe.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/APrincesaQueSalvaPrincipe.jpg?raw=true"

  },
  {
    id: 96,
    titulo: "Mario Juruna",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Feminino",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Juruna.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Juruna.jpg?raw=true"

  },
  {
    id: 97,
    titulo: "Davi Kopenawa",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Empoderamento Negro",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Kopenawa.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Kopenawa.jpg?raw=true"

  },
  {
    id: 98,
    titulo: "Ailton Krenak",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Coleção Black Power",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Krenak.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Krenak.jpg?raw=true"

  },
  {
    id: 99,
    titulo: "Laudelina de Campos de Melo",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Coleção Black Power",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Laudelina.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Laudelina.jpg?raw=true"

  },
  {
    id: 100,
    titulo: "Luiz Gama",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Coleção Black Power ",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
     capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Luiz.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Luiz.jpg?raw=true"

  },

  {
    id: 101,
    titulo: "Nelson Mandela",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Coleção Black Power",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Mandela.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Mandela.jpg?raw=true"

    
  },
 {
    id: 102,
    titulo: "Machado de Asis",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Coleção Black Power",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Machado.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Machado.jpg?raw=true"

    
  },
  {
    id: 102,
    titulo: "Machado de Asis",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Coleção Black Power",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Machado.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Machado.jpg?raw=true"

    
  },
{
    id: 103,
    titulo: "Malcolm X",
    autor: "s/a",
    editora: "Mostarda",
    tema: "Coleção Black Power",
    genero: "Biografia infantojuvenil",
    numeroPaginas: 32,
    dataPublicacao: "2021",
    isbn: null,
    capa: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Malcolm.jpg?raw=true",
    mostruario: "https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Malcolm.jpg?raw=true"

    
  },


];

 // Cabeçalhos CORS padrão
    const corsHeaders = {
  "Access-Control-Allow-Origin": "*", // ou "http://localhost:3000"
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type", // CORRIGIDO
  "Content-Type": "application/json",
};


    // OPTIONS (preflight)
    if (method === "OPTIONS") {
      return new Response(null, {
        status: 204,
        headers: corsHeaders,
      });
    }

    // Rota: /livros/:id
    const matchId = pathname.match(/^\/livros\/(\d+)$/);
    if (matchId) {
      const id = parseInt(matchId[1]);
      const livro = livros.find((l) => l.id === id);

      if (livro) {
        return new Response(JSON.stringify(livro), {
          status: 200,
          headers: corsHeaders,
        });
      } else {
        return new Response(JSON.stringify({ erro: "Livro não encontrado" }), {
          status: 404,
          headers: corsHeaders,
        });
      }
    }

    // Rota: /livros (lista completa)
    if (pathname === "/livros") {
      return new Response(JSON.stringify(livros), {
        status: 200,
        headers: corsHeaders,
      });
    }

    // Rota não encontrada
    return new Response(JSON.stringify({ erro: "Rota não encontrada" }), {
      status: 404,
      headers: corsHeaders,
    });
  },
};