
export default {
  async fetch(request) {
    const { method, url } = request;
    const { pathname } = new URL(url);


	  // Dados simulados (substitua por sua lógica real)
	    const livros = [
       {
     id : 1,
    titulo: "A Princesa que Salvava Príncipes",
    autor: "Claudia Souza",
    editora: "Callis",
    tema: "Empoderamento feminino",
    genero: "Fantasia",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Neste conto de fadas moderno, a princesa não é uma jovem fraca que desmaia diante do dragão. Contrariando todas as expectativas, ela invade o quarto da bruxa e enfrenta quadros com bocas e olhos de verdade, tudo para resgatar o príncipe.",
    dataPublicacao: "2012-01-01",
    dataCatalogo: "2025-05-18",
    capa: "./192.168.0.104:8081/assets/?unstable_path=.%2Fassets%2Fimages%2Fcapa/APrincesaQueSalvaPrincipe.jpg",
    mostruario: "./192.168.0.104:8081/assets/?unstable_path=.%2Fassets%2Fimages%2Fthumbnaill/APrincesaQueSalvaPrincipe.jpg"
  },
  {
    id: 2,
    titulo: "A Ginga da Rainha",
    autor: "Iris Maria da Costa Amâncio",
    editora: "Mazza Edições",
    tema: "Empoderamento feminino",
    genero: "Educativo",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 40,
    resumo: "A história da rainha Nzinga, uma das mulheres mais importantes da história africana, que lutou contra a escravidão e a colonização em Angola. Um livro que valoriza a cultura afro-brasileira e a resistência feminina.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-05-25",
    capa: "./192.168.0.104:8081/assets/?unstable_path=.%2Fassets%2Fimages%2Fcapa/AGingaRainha.jpg",
    mostruario: "./192.168.0.104:8081/assets/?unstable_path=.%2Fassets%2Fimages%2Fthumbnaill/AGingaRainha.jpg"
  },
  {
    id: 3,
    titulo: "O Menino Azul",
    autor: "Cecília Meireles, Lúcia Hiratsuka",
    editora: "Global Editora",
    tema: "Infância / Imaginação / Amizade",
    genero: "Poesia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Um poema clássico de Cecília Meireles, ilustrado por Lúcia Hiratsuka, que fala sobre o desejo de uma criança por um burrinho para viver aventuras e alimentar sua imaginação.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-05-25",
    capa: "./192.168.0.104:8081/assets/?unstable_path=.%2Fassets%2Fimages%2Fcapa/CecíliaMeirelesMeninoAzul.jpg",
    mostruario: "./192.168.0.104:8081/assets/?unstable_path=.%2Fassets%2Fimages%2Fthumbnaill/CecíliaMeirelesMeninoAzul.jpg"
  },

{
  id: 4,
  titulo: "ABC da Capoeira",
  autor: "Victor Alvim I. Garcia",
  editora: "Victor Alvim",
  tema: "Capoeira",
  genero: "Educativo",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 48,
  resumo: "Este livro apresenta de forma educativa e acessível os fundamentos da capoeira, suas origens, movimentos e importância cultural. Voltado para o público jovem, busca ensinar valores históricos e sociais por meio da prática dessa arte afro-brasileira.",
  dataPublicacao: "2006-01-01",
  dataCatalogo: "2025-06-13",
  capa: "./192.168.0.104:8081/assets/?unstable_path=./assets/images/capa/ABCDaCapoeira.jpg",
  mostruario: "./192.168.0.104:8081/assets/?unstable_path=./assets/images/thumbnaill/ABCDaCapoeira.jpg"
},
{
  id: 5,
  titulo: "África; conto do rio, da selva e da savana",
  autor: "Silvana Salerno",
  editora: "Girassol",
  tema: "Mitologia",
  genero: "Contos",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 56,
  resumo: "Reunindo histórias passadas de geração em geração no continente africano, o livro convida o leitor a mergulhar em contos que se desenrolam às margens dos rios, nas florestas densas e nas vastas savanas. Uma celebração da oralidade e da diversidade cultural da África.",
  dataPublicacao: "2009-01-01",
  dataCatalogo: "2025-06-13",
  capa: "./192.168.0.104:8081/assets/?unstable_path=./assets/images/capa/AfricaContoRioSelvaSavana.jpg",
  mostruario: "./192.168.0.104:8081/assets/?unstable_path=./assets/images/thumbnaill/AfricaContoRioSelvaSavana.jpg"
},

{
  id: 6,
  titulo: "A África que você fala",
  autor: "Claudio Fragata",
  editora: "Globinho",
  tema: "Linguística",
  genero: "Educativo",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 32,
  resumo: "Apresenta de forma leve e ilustrada palavras de origem africana incorporadas ao português, explicando suas raízes em quimbundo, iorubá, jeje e banto.",
  dataPublicacao: "15-01-2021",
  dataCatalogo: "2025-06-13",
  capa: "./capa/AFricaqueVoceFala.jpg",
  mostruario: "./thumbnaill/AFricaqueVoceFala.jpg"
},
{
  id: 7,
  titulo: "África recontada para crianças",
  autor: "Avani Souza Silva",
  editora: "Martin Claret",
  tema: "História",
  genero: "Contos",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 64,
  resumo: "Reconta lendas e histórias do continente africano em formato acessível para crianças, valorizando a oralidade e a diversidade cultural.",
  dataPublicacao: "2019-01-01",
  dataCatalogo: "2025-06-13",
  capa: "./capa/AfricaRecontadaCrianças.jpg",
  mostruario: "./thumbnaill/AfricaRecontadaCrianças.jpg"
},

{
  id: 8,
  titulo: "Aqui no morro, tem princesa sim!",
  autor: "Simone Botelho",
  editora: "Albatrozinho",
  tema: "Empoderamento feminino",
  genero: "Poesia",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 40,
  resumo: "Uma princesa que vive no morro e quebra estereótipos tradicionais de fadas: real, forte, periférica e protagonista de sua própria história.",
  dataPublicacao: "2020-01-01",
  dataCatalogo: "2025-06-13",
  capa: "./capa/AquiNoMorroTemPrincesaSim.jpg",
  mostruario: "./thumbnaill/AquiNoMorroTemPrincesaSim.jpg"
},

{
  id: 8,
  titulo: "Amoras",
  autor: "Emicida",
  editora: "Companhia das Letrinhas",
  tema: "Autoconhecimento / Representatividade",
  genero: "Poesia",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 44,
  resumo: "Inspirado na música 'Amoras', o livro celebra a autoestima e o orgulho racial desde a infância, por meio de texto poético e ilustrações suaves.",
  dataPublicacao: "14-09-2018",
  dataCatalogo: "2025-06-13",
  capa: "./capa/Amoras.jpg",
  mostruario: "./thumbnaill/Amoras.jpg"
},

{
  id: 9,
  titulo: "Amor de cabelo",
  autor: "Matthew A. Cherry",
  editora: "Galerinha",
  tema: "Autoestima",
  genero: "conto",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 32,
  resumo: "Baseado no curta vencedor do Oscar “Hair Love”, o livro narra o carinho entre pai e filha enquanto eles encontram o penteado perfeito para celebrar um momento especial, valorizando o cabelo crespo e o amor familiar.",
  dataPublicacao: "04-05-2020",
  dataCatalogo: "2025-06-13",
  capa: "./capa/AmorDeCabelo.jpg",
  mostruario: "./thumbnaill/AmorDeCabelo.jpg"
},
{
  id: 10,
  titulo: "Batismo da Capoeirinha (confusão no Quintal)",
  autor: "Sérgio Ballouk",
  editora: "Quilombhoje",
  tema: "Capoeira",
  genero: "Cultura",
  classificacaoLiteraria: "Infantojuvenil",
  numeroPaginas: 48,
  resumo: "A pequena capoeirinha vive uma divertida confusão no quintal durante seu batizado simbólico como capoeirista, entre rodas improvisadas, batuques e a comunidade que a acompanha.",
  dataPublicacao: "2018-01-01",
  dataCatalogo: "2025-06-13",
  capa: "./capa/BatismoDaCapoeirinha.jpg",
  mostruario: "./thumbnaill/BatismoDaCapoeirinha.jpg"
},
{
  id: 11,
  titulo: "Beata; a menina das águas",
  autor: "Elaine Marcelina",
  editora: "Malê mirim",
  tema: "Religioso",
  genero: "Biografia",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 24,
  resumo: "Baseado na infância de Mãe Beata de Iemanjá, a obra mostra a ligação espiritual da menina com a natureza, celebrando sua vocação e legado de resistência religiosa :contentReference[oaicite:1]{index=1}.",
  dataPublicacao: "17-04-2021",
  dataCatalogo: "2025-06-13",
  capa: "./capa/BeataAMeninaDasAguas.jpg",
  mostruario: "./thumbnaill/BeataAMeninaDasAguas.jpg"
},
{
  id: 12,
  titulo: "Betina",
  autor: "Nilma Lino Gomes",
  editora: "Maza Edições",
  tema: "Empoderamento",
  genero: "Reflexão",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 32,
  resumo: "Através da personagem Betina, o livro promove reflexão sobre a autoestima e a identidade negra desde a infância, com linguagem acessível e imagens evocativas.",
  dataPublicacao: "2022-01-01",
  dataCatalogo: "2025-06-13",
  capa: "./capa/Betina.jpg",
  mostruario: "./thumbnaill/Betina.jpg"
},
{
  id: 13,
  titulo: "Bolota; uma certa jabuticaba muito esperta",
  autor: "Iray Galrão",
  editora: "Escritinha",
  tema: "Aventura",
  genero: "Conto",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 40,
  resumo: "A história acompanha Bolota, uma jabuticaba curiosa e destemida, em aventuras pela mata, ensinando sobre amizade, ecologia e o ciclo da vida de forma divertida.",
  dataPublicacao: "2021-01-01",
  dataCatalogo: "2025-06-13",
  capa: "./capa/BolotaJabuticaba.jpg",
  mostruario: "./thumbnaill/BolotaJabuticaba.jpg"
},
{
  id: 14,
  titulo: "Brincar na rua",
  autor: "Magna Domingues",
  editora: "Baú Encantado",
  tema: "Infância",
  genero: "Poesia",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 36,
  resumo: "Uma celebração poética da infância, do brincar na rua e da inventividade das crianças que transformam a rua em palco de suas histórias cotidianas e sonhos.",
  dataPublicacao: "2020-01-01",
  dataCatalogo: "2025-06-13",
  capa: "./capa/BrincarNaRua.jpg",
  mostruario: "./thumbnaill/BrincarNaRua.jpg"
},

{
   id: 15,
  titulo:   "Bruna e a Galinha d’Angola",
  autor: "Gercilga de Almeida",
  editora: "EDC e Pallas",
  tema: "Mitologia",
  genero: "Literatura",
  classificacaoLiteraria: "Infantil",
  numeroPaginas: 24,
  resumo: "Primeiro livro infantil a retratar o universo mítico africano, contando de forma lúdica e didática como a galinha-d’angola participou da criação do mundo, a partir da curiosidade de Bruna e das narrativas de sua avó travessa.",
  dataPublicacao:"19-03-2009",
  capa: "./capa/BrunaEGalinhaDAngola.jpg",
  mostruario: "./thumbnaill/BrunaEGalinhaDAngola.jpg"
},

 {
        id: 16,
        titulo: "Bucala; a pequena princesa do Quilombo Cabula",
        autor: "Davi Nunes",
        editora: "Malê Mirim",
        tema: "Historia",
        genero: "Aventura",
        classificacaoLiteraria: "Infantojuvenil",
        numeroPaginas: 32,
        resumo: "Bucala é uma princesa quilombola que vive no Quilombo do Cabula no século XIX...",
        dataPublicacao: "2019-01-01",
        dataCatalogo: "2025-06-13",
        capa: "./capa/BucalaPrincesaQuilomboCabula.jpg",
        mostruario: "./thumbnaill/BucalaPrincesaQuilomboCabula.jpg"
      },

 {
    id: 17,
    titulo: "Calu; uma menina cheia de histórias",
    autor: "Cássia Valle",
    ilustrador: "Maria Chantal",
    editora: "Malê Mirim",
    tema: "cultura",
    genero: "Ficção",
    classificacao: "Infantojuvenil",
    paginas: 32,
    resumo: "A protagonista Calu transforma seu bairro em um 'museu a céu aberto', celebrando a cultura local e fortalecendo o sentimento de pertencimento e preservação do patrimônio imaterial.",
    data_publicacao: "2017-01-02",
    data_catalogo: "2025-06-17",
    url_capa: "./capa/CaluMeninaHistorias.jpg",
    url_mostruario: "./thumbnaill/CaluMeninaHistorias.jpg"
  },
  {
    id: 18,
    titulo: "Chuva de manga",
    autor: "James Rumford",
    editora: "Brinque-Book",
    tema: "Cultura",
    genero: "Literatura",
    classificacao: "Infantojuvenil",
    paginas: 32,
    resumo: "No Chade, o menino Tomás celebra as chuvas que o tornam fértil, colhendo mangas e construindo um carrinho de lata. Uma narrativa que constrói empatia cultural e convida à reflexão sobre valores simples e universais.",
    data_publicacao: "2005-11-04",
    data_catalogo: "2025-06-17",
    url_capa: "./capa/ChuvaDeManga.jpg",
    url_mostruario: "./thumbnaill/ChuvaDeManga.jpg"
  },
{
  id: 19,
    titulo: "Com qual penteado eu vou?",
    autor: "Kiusam de Oliveira",
    ilustrador: "Rodrigo Andrade",
    editora: "Melhoramentos",
    tema: "Autoestima",
    genero: "Conto",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 48,
    resumo: "Durante a festa de 100 anos do bisavô Seu Benedito, as bisnetas escolhem penteados especiais e presenteiam o centenário com as virtudes que mais admiram, celebrando ancestralidade, família, negritude e representatividade capilar.",
    dataPublicacao: "2021-06-04",
    dataCatalogo: "2025-06-17",
    capa: "./capa/ComQualPenteadoEuVou.jpg",
    mostruario: "./thumbnaill/ComQualPenteadoEuVou.jpg"
  },
  {
    id: 20,
    titulo: "Contos de Monadenge",
    autor: "Israel Neto e Jader Oliveira",
    ilustrador: "Soberana Ziza",
    editora: "Literatura suburbana e literária besouro",
    tema: "Mitologia",
    genero: "Contos",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Monadenge, contador de histórias do quilombo de Alquatune, narra dois contos fantásticos às crianças, conectando passado africano e legado quilombola em um resgate poético das raízes.",
    dataPublicacao: "2023-01-01", // geralmente volumes da coleção são recentes ,
    dataCatalogo: "2025-06-17",
    capa: "./capa/ContosDeMonadenge.jpg",
    mostruario: "./thumbnaill/ContosDeMonadenge.jpg"
  },
  {
    id: 21,
    titulo: "De grão em grão, o sucesso vem na mão",
    autor: "Katie Smith Milway",
    ilustrador: "Eugenie Fernandes",
    editora: "Melhoramentos",
    tema: "Superação / Educação financeira",
    genero: "Biografia",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Inspirado em fatos reais, conta a trajetória de Kojo, menino que ajuda a mãe vendendo ovos, volta à escola, obtém empréstimos e constrói uma granja — um poderoso relato sobre resiliência e futuro.",
    dataPublicacao: "2008-11-08",
    dataCatalogo: "2025-06-17",
    capa: "./capa/DeGraoEmGraoSucesso.jpg",
    mostruario: "./thumbnaill/DeGraoEmGraoSucesso.jpg"
  },

  {
    id: 22,
    titulo: "Dengos na moringa de voinha",
    autor: "Ana Fátima",
    ilustrador: "Fernanda Rodrigues",
    editora: "Brinque‑Book",
    tema: "Ancestralidade",
    genero: "Conto",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "A história aproxima o leitor dos pequenos gestos do cotidiano familiar — carinhos, cheiros, danças — contados pela moringa de Voinha, objeto que simboliza a ancestralidade e os afetos herdados da família quilombola em uma crônica poética e delicada.",
    dataPublicacao: "2023-06-27",
    dataCatalogo: "2025-06-17",
    capa: "./capa/DengosNaMoringa.jpg",
    mostruario: "./thumbnaill/DengosNaMoringa.jpg"
  },
  {
    id: 23,
    titulo: "De passinho em passinho",
    autor: "Otávio Júnior",
    ilustrador: "Bruna Lubambo",
    editora: "Companhia das Letrinhas",
    tema: "Cultura / Dança",
    genero: "Prosa / poema ",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Livro que celebra o passinho — dança urbana carioca com influências do funk, capoeira, samba e frevo —, retratando sonhos, movimento e representatividade, com texto poético e ilustrações vibrantes.",
    dataPublicacao: "2021-07-13",
    dataCatalogo: "2025-06-17",
    capa: "./capa/DePassinhoEmPassinho.jpg",
    mostruario: "./thumbnaill/DePassinhoEmPassinho.jpg"
  },
  {
    id: 24,
    titulo: "Descobertas de Kito",
    autor: "Douglas Coelho",
    editora: "Letraria",
    tema: "Educacional",
    genero: "Didático",
    classificacaoLiteraria: "Infatil",  // faltam dados online, estimado
    numeroPaginas: 40,                 // estimado
    resumo: "Kito, uma criança curiosa, explora o mundo ao seu redor, levantando perguntas sobre plantas, animais e fenômenos, de forma lúdica e incentivando o pensamento crítico e científico desde cedo.",
    dataPublicacao: "2022-01-01",      // estimado,
    dataCatalogo: "2025-06-17",
    capa: "",
    mostruario: ""
  },
  {
    id: 25,
    titulo: "ÉDÁ, EDÁ - as palavras e cores da criação Òkè",
    autor: "Mariana Moretti e Luiz Carlos Garcia",
    ilustrador: "Mariana Moretti",
    editora: "Literatura suburbana e literária besouro",
    tema: "Mitologia",
    genero: "Literatura",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "Inspirado nas narrativas iorubás sobre a criação do mundo, o livro apresenta a cosmogonia Òkè através de imagens coloridas e linguagem poética. Um convite à imaginação e à valorização das raízes africanas.",
    dataPublicacao: "2023-10-01",
    dataCatalogo: "2025-06-17",
    capa: "",
    mostruario: ""
  },
  {
    id: 26,
    titulo: "Eu, curiosa?",
    autor: "Flavia da Cruz e Cátia Luciana Pereira",
    ilustrador: "Júlia Lima",
    editora: "Literatura suburbana e literária besouro",
    tema: "Infância",
    genero: " Narrativa / Poema",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Uma menina negra cheia de perguntas embarca em descobertas sobre si mesma, sobre a vida e sobre o mundo. O livro propõe uma valorização da infância negra através da curiosidade e imaginação.",
    dataPublicacao: "2023-07-01",
    dataCatalogo: "2025-06-17",
    capa: "",
    mostruario: ""
  },
  {
    id: 27,
    titulo: "Era dos Erês; uma era ao culto da natureza e dos orixás",
    autor: "Adriano Bitarães Netto",
    ilustrador: "Mariana Barcelos",
    editora: "Maza Edições",
    tema: "Religiões",
    genero: "Didático",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 40,
    resumo: "A obra apresenta os Erês, entidades infantis da mitologia afro-brasileira, e sua relação com os orixás e a natureza. Um livro que resgata saberes sagrados com linguagem acessível e ilustrações simbólicas.",
    dataPublicacao: "2021-11-15",
    dataCatalogo: "2025-06-17",
    capa: "",
    mostruario: ""
  },

    {
    id: 28,
    titulo: "Férias fantásticas de Lili",
    autor: "Lívia Natália",
    ilustrador: "Carolina Teixeira",
    editora: "Ciclo Contínuo",
    tema: "Cultura",
    genero: "Poesia ",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 48,
    resumo: "Lili revive suas férias na Bahia, entre lagoas, praia e memórias de encantamentos da infância, vivenciados à beira do Abaeté e cheios de magia e religiosidade ligada aos Orixás.",
    dataPublicacao: "2018-09-30",
    dataCatalogo: "2025-06-17",
    capa: "",
    mostruario: ""
  },
  {
    id: 29,
    titulo: "Foi assim que eu e a escuridão ficamos amigas",
    autor: "Emicida",
    ilustrador: "Aldo Fabrini",
    editora: "Companhia das Letrinhas",
    tema: "emoção",
    genero: "Poesia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "Duas meninas‑personificações do dia e da noite se conhecem e descobrem que, apesar dos medos iniciais, podem se tornar amigas, em narrativa poética que trata ansiedade e empoderamento emocional.",
    dataPublicacao: "2020-10-05",
    dataCatalogo: "2025-06-17",
    capa: "./capa/FoiAssimEscuridaoAmigas.jpg",
    mostruario: "./thumbnaill/FoiAssimEscuridaoAmigas.jpg"
  },
  {
    id: 30,
    titulo: "Gabriela; a princesa do Daomé",
    autor: "Marta Rodrigues",
    ilustrador: "Não informado",
    editora: "Maza Edições",
    tema: "História",
    genero: "Biografia",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32, // estimado
    resumo: "Gabriela é retratada como jovem princesa do antigo reino do Daomé, em território da atual Benim, seu percurso inspira reflexão sobre o poder feminino e a história africana.",
    dataPublicacao: "2022-01-01", // estimado,
    dataCatalogo: "2025-06-17",
    capa: "",
    mostruario: ""
  },

   {
    id: 32,
    titulo: "Gosto de África: história de lá e daqui",
    autor: "Joel Rufino dos Santos",
    ilustrador: "Pedro Rafael",
    editora: "Global",
    tema: "História / Cultura",
    genero: " Conto ",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "O livro apresenta histórias que aproximam as culturas africana e afro-brasileira, celebrando suas raízes e influências no cotidiano e na história do Brasil.",
    dataPublicacao: "2007-01-01",
    dataCatalogo: "2025-06-17",
    capa: "",
    mostruario: ""
  },
  {
    id: 33,
    titulo: "Histórias Africanas para contar e recontar",
    autor: "Rogério Andrade Barbosa",
    ilustrador: "Martinho de Haro",
    editora: "Editora do Brasil",
    tema: "Cultura",
    genero: "Conto",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Coletânea de contos africanos, com lições de vida, valores e tradições, pensada para preservar a sabedoria dos griôs e incentivar a oralidade nas crianças.",
    dataPublicacao: "2003-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.editoradobrasil.com.br/wp-content/uploads/2017/09/Hist%C3%B3rias-Africanas-para-contar-e-recontar-1.jpg",
    mostruario: "/www.editoradobrasil.com.br/wp-content/uploads/2017/09/Hist%C3%B3rias-Africanas-para-contar-e-recontar-1-150x150.jpg"
  },
  {
    id: 34,
    titulo: "Histórias do tio Jimbo",
    autor: "Nei Lopes",
    ilustrador: "Não informado",
    editora: "Maza Edições",
    tema: "eucacional",
    genero: "Conto / Narrativa",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 40,
    resumo: "O Tio Jimbo, griô africano, narra contos divertidos e educativos sobre a vida, os valores e os deuses africanos, promovendo uma imersão cultural.",
    dataPublicacao: "2007-01-01", // estimado,
    dataCatalogo: "2025-06-17",
    capa: "./capa/HistoriaTioJimbo.jpg",
    mostruario: "./thumbnaill/HistoriaTioJimbo.jpg"
  },
  {
    id: 35,
    titulo: "Ifá, o Adivinho",
    autor: "Reginaldo Prandi",
    ilustrador: "Pedro Rafael",
    editora: "Companhia das Letrinhas",
    tema: "Religião",
    genero: "Conto",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Baseado no sistema de adivinhação Ifá, o livro apresenta contos que explicam a sabedoria do oráculo africano e o papel dos Orixás na orientação das pessoas.",
    dataPublicacao: "2004-08-01",
    dataCatalogo: "2025-06-17",
    capa: "/img.skoob.com.br/FdpNfVCOemhAYF1a-QpIEavb8ZE=/600x0/center/top/filters:format(jpeg)//skoob.s3.amazonaws.com/livros/471/IFA_O_ADIVINHO_1293580152B.jpg",
    mostruario: "/img.skoob.com.br/FdpNfVCOemhAYF1a-QpIEavb8ZE=/150x150/center/top/filters:format(jpeg)//skoob.s3.amazonaws.com/livros/471/IFA_O_ADIVINHO_1293580152B.jpg"
  },
  {
    id: 36,
    titulo: "Igbo e as princesas",
    autor: "Marcos Cajé",
    ilustrador: "Não informado",
    editora: "Marcos Cajé",
    tema: "Mitologia",
    genero: "aventura",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 28,
    resumo: "Através da jornada de Igbo e das princesas, o autor apresenta elementos mitológicos africanos e valores como solidariedade, honra e ancestralidade.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "./capa/IgboPrincesas.jpg",
    mostruario: "./thumbnaill/IgboPrincesas.jpg"
  },
  {
    id: 37,
    titulo: "Jongo",
    autor: "Sonia Rosa",
    ilustrador: "Mauricio Negro",
    editora: "Pallas",
    tema: "Cultura afro-brasileira / Dança e música / Herança africana",
    genero: "Infantil / História",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "O livro apresenta o Jongo, dança de origem africana trazida por negros escravizados, mostrando sua musicalidade, oralidade e importância cultural no Brasil.",
    dataPublicacao: "2007-06-01",
    dataCatalogo: "2025-06-17",
    capa: "/img.travessa.com.br/livro/BA/63/63b165a2-d09e-4a2b-9e59-fc68cfad325e.jpg",
    mostruario: "/img.travessa.com.br/livro/BA/63/63b165a2-d09e-4a2b-9e59-fc68cfad325e_150x150.jpg"
  },

   {
    id: 38,
    titulo: "Nós de Axé",
    autor: "Janaína de Figueiredo",
    editora: "Aletria",
    tema: "Religiões afro-brasileiras / Candomblé / Infância",
    genero: "Infantil / Religioso",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "História sensível que introduz elementos do Candomblé e da ancestralidade com respeito e afeto para crianças.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/aletria.com.br/wp-content/uploads/2022/09/nos-de-axe.jpg",
    mostruario: "/aletria.com.br/wp-content/uploads/2022/09/nos-de-axe-150x150.jpg"
  },
  {
    id: 39,
    titulo: "Nove pentes d'África",
    autor: "Cidinha da Silva",
    editora: "Maza Edições",
    tema: "Afrofuturismo / Tradição africana / Identidade",
    genero: "Infantil / Fantasia",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 44,
    resumo: "Garota viaja por nove reinos africanos em busca de pentes mágicos, aprendendo sobre história, autoestima e empoderamento.",
    dataPublicacao: "2019-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/nove-pentes.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/nove-pentes-150x150.jpg"
  },
  {
    id: 40,
    titulo: "Obax",
    autor: "André Neves",
    editora: "Brinque-book",
    tema: "Imaginação / Cultura africana / Natureza",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Obax é uma menina cheia de sonhos que transforma sua aldeia com a força de sua imaginação e conexão com a natureza.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.brinquebook.com.br/wp-content/uploads/2019/09/obax.jpg",
    mostruario: "/www.brinquebook.com.br/wp-content/uploads/2019/09/obax-150x150.jpg"
  },

    {
    id: 41,
    titulo: "Koumba e o Tambor Diambê",
    autor: "Madu Costa",
    ilustrador: "Não informado",
    editora: "Pallas",
    tema: "Tradições africanas / Mitologia / Cultura oral",
    genero: "Infantil / Conto",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Koumba é um jovem africano que herda o tambor mágico de seu avô. A história valoriza a ancestralidade e o poder da música como elo cultural.",
    dataPublicacao: "2011-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/img.travessa.com.br/livro/BA/8f/8f20fc1e-400c-4036-85ef-157b3e8e3ef9.jpg",
    mostruario: "/img.travessa.com.br/livro/BA/8f/8f20fc1e-400c-4036-85ef-157b3e8e3ef9_150x150.jpg"
  },
  {
    id: 42,
    titulo: "Lenço de cetim da mamãe",
    autor: "Chimamanda Ngozi Adichie / Nwa Grace-James",
    ilustrador: "Joelle Avelino",
    editora: "Companhia das Letrinhas",
    tema: "Feminismo / Tradição africana / Família",
    genero: "Infantil / Narrativa contemporânea",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Baseado em conto de Chimamanda, o livro retrata a relação de uma criança com sua mãe e os símbolos culturais herdados, como o lenço de cetim.",
    dataPublicacao: "2022-05-01",
    dataCatalogo: "2025-06-17",
    capa: "/img.travessa.com.br/livro/BA/94/943d28aa-6a77-4791-922c-7465ae35663f.jpg",
    mostruario: "/img.travessa.com.br/livro/BA/94/943d28aa-6a77-4791-922c-7465ae35663f_150x150.jpg"
  },
  {
    id: 43,
    titulo: "Lendas de Dandara",
    autor: "Jarid Arraes",
    ilustrador: "Não informado",
    editora: "Cultura",
    tema: "História / Resistência negra / Quilombos",
    genero: "Infantil / Biográfico-ficcional",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 48,
    resumo: "Reconta lendas inspiradas na guerreira Dandara dos Palmares, abordando temas de luta, liberdade e protagonismo feminino negro.",
    dataPublicacao: "2015-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/pbs.twimg.com/media/EN4Bx71XsAAzAaS.jpg",
    mostruario: "/pbs.twimg.com/media/EN4Bx71XsAAzAaS?format=jpg&name=small"
  },
  {
    id: 44,
    titulo: "Letras de Carvão",
    autor: "Irene Vasco e Juan Palomino",
    ilustrador: "Juan Palomino",
    editora: "Pulo do Gato",
    tema: "Alfabetização / Superação / Povos tradicionais",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Menina da zona rural aprende a ler e escrever, superando obstáculos. Homenagem à educação e à força das comunidades marginalizadas.",
    dataPublicacao: "2016-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.pulodogatoeditora.com.br/media/2020/04/letras-de-carvao.jpg",
    mostruario: "/www.pulodogatoeditora.com.br/media/2020/04/letras-de-carvao-150x150.jpg"
  },
  {
    id: 45,
    titulo: "Luz de Aisha",
    autor: "Aza Njeri e Luana Rodrigues",
    ilustrador: "Não informado",
    editora: "Rebuliço",
    tema: "Espiritualidade / Ancestralidade / Candomblé",
    genero: "Infantil / Religioso-cultural",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 36,
    resumo: "Aisha vive uma jornada de descoberta sobre sua herança iorubá e a presença dos Orixás em sua vida cotidiana.",
    dataPublicacao: "2023-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/rebulico.com.br/wp-content/uploads/2023/04/luz-de-aisha.png",
    mostruario: "/rebulico.com.br/wp-content/uploads/2023/04/luz-de-aisha-150x150.png"
  },
  {
    id: 46,
    titulo: "Makeba vai à Escola",
    autor: "Ana Fátima",
    ilustrador: "Não informado",
    editora: "Cogito",
    tema: "Educação / Autoestima negra / Empoderamento",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Makeba é uma menina negra que enfrenta o primeiro dia de aula lidando com sua identidade, cabelo e aceitação, com leveza e representatividade.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.editoracogito.com.br/uploads/2/6/1/6/26160438/s704845316771925537_p14_i2_w1920.jpeg",
    mostruario: "/www.editoracogito.com.br/uploads/2/6/1/6/26160438/s704845316771925537_p14_i2_w150.jpeg"
  },
  {
    id: 47,
    titulo: "Makori; a pequena princesa",
    autor: "Marcos Cajé",
    ilustrador: "Não informado",
    editora: "Ereginga Educação",
    tema: "Tradição africana / Contos de princesas negras",
    genero: "Infantil / Conto de fadas africano",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 30,
    resumo: "Makori é uma jovem princesa africana que aprende sobre valores e ancestralidade através de aventuras com animais sagrados.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "./makori.jpg",
    mostruario: "./makori_thumb.jpg"
  },
  {
    id: 48,
    titulo: "Mandisa e a vovó Alegria",
    autor: "Vagner Amaro",
    ilustrador: "Não informado",
    editora: "Malê Mirim",
    tema: "Sabedoria ancestral / Relação avó-neta / Cultura afro",
    genero: "Infantil",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 28,
    resumo: "Mandisa aprende com sua avó sobre as histórias de seu povo, costumes africanos e valores como afeto, respeito e autoestima.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/editoramale.com.br/wp-content/uploads/2021/07/mandisa_vovo_alegria.jpg",
    mostruario: "/editoramale.com.br/wp-content/uploads/2021/07/mandisa_vovo_alegria-150x150.jpg"
  },
  {
    id: 49,
    titulo: "Mar de Manu",
    autor: "Cidinha da Silva",
    ilustrador: "Não informado",
    editora: "Kuanza Produções",
    tema: "Imaginação / Emoções / Infância",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Manu navega por mares simbólicos que representam suas emoções e sua ancestralidade, em um texto lírico e sensível.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/kuanza.com.br/wp-content/uploads/2022/07/mar-de-manu.jpg",
    mostruario: "/kuanza.com.br/wp-content/uploads/2022/07/mar-de-manu-150x150.jpg"
  },
  {
    id: 50,
    titulo: "Meninas negras",
    autor: "Madu Costa",
    ilustrador: "Não informado",
    editora: "Mazza",
    tema: "Representatividade / Empoderamento / Meninas negras",
    genero: "Infantil / Poesia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Uma homenagem poética à força, beleza e diversidade das meninas negras, com ilustrações vibrantes e mensagens de autoestima.",
    dataPublicacao: "2018-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.mazzaedicoes.com.br/wp-content/uploads/2019/08/meninasnegras.jpg",
    mostruario: "/www.mazzaedicoes.com.br/wp-content/uploads/2019/08/meninasnegras-150x150.jpg"
  },
  {
    id: 51,
    titulo: "Menina Nicinha",
    autor: "Evelyn Sacramento",
    ilustrador: "Não informado",
    editora: "Lendo Mulheres Negras / Aldir Blanc Bahia",
    tema: "Identidade / Família / Cultura baiana",
    genero: "Infantil",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 36,
    resumo: "Nicinha vive uma história sensível sobre identidade, convivência familiar e descobertas no contexto de sua cultura local afro-baiana.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/lendomulheresnegras.com.br/wp-content/uploads/2022/10/menina-nicinha.jpg",
    mostruario: "/lendomulheresnegras.com.br/wp-content/uploads/2022/10/menina-nicinha-150x150.jpg"
  },

  {
    id: 52,
    titulo: "Menino voador e o aprendiz de vagalume",
    autor: "Jota Revella e Regina Alonso",
    editora: "Literatura Suburbana e Literária Besouro",
    tema: "Imaginação / Sonhos / Realidade urbana",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 36,
    resumo: "Um menino e seu avô compartilham sonhos e histórias que iluminam a infância em meio à realidade da periferia.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.literaturasuburbana.com.br/img/menino-voador.jpg",
    mostruario: "/www.literaturasuburbana.com.br/img/menino-voador-thumb.jpg"
  },
  {
    id: 53,
    titulo: "Menino coração de tambor",
    autor: "Nilma Lino Gomes",
    editora: "Maza Edições",
    tema: "Cultura afro-brasileira / Musicalidade / Identidade",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Narrativa sobre um menino que encontra no tambor um elo com suas raízes, fortalecendo sua autoestima e cultura.",
    dataPublicacao: "2007-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2022/03/menino-coracao.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2022/03/menino-coracao-150x150.jpg"
  },
  {
    id: 54,
    titulo: "Minha dança tem história",
    autor: "Bell Hooks e Chris Raschka",
    editora: "Boi ta tá",
    tema: "Autoestima / Movimento / Cultura negra",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Poema de bell hooks traduzido com imagens expressivas, reforçando orgulho do corpo negro e suas expressões culturais.",
    dataPublicacao: "2018-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/boitata.curitiba.br/wp-content/uploads/2018/10/minha-danca-tem-historia.jpg",
    mostruario: "/boitata.curitiba.br/wp-content/uploads/2018/10/minha-danca-tem-historia-thumb.jpg"
  },
  {
    id: 55,
    titulo: "Minha mãe é negra sim!",
    autor: "Patrícia Santana",
    editora: "Maza Edições",
    tema: "Identidade racial / Família / Representatividade",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Menina aprende a reconhecer a beleza e força de sua mãe negra em uma história afetuosa sobre orgulho racial.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/minha-mae-e-negra-sim.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/minha-mae-e-negra-sim-150x150.jpg"
  },
  {
    id: 56,
    titulo: "Meu crespo é de rainha",
    autor: "Bell Hooks",
    editora: "Boi ta tá",
    tema: "Autoestima / Cabelo crespo / Orgulho",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Poema de empoderamento que celebra os cabelos crespos e sua beleza única, com ilustrações vibrantes.",
    dataPublicacao: "2018-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/boitata.curitiba.br/wp-content/uploads/2018/04/meu-crespo.jpg",
    mostruario: "/boitata.curitiba.br/wp-content/uploads/2018/04/meu-crespo-thumb.jpg"
  },
  {
    id: 57,
    titulo: "Neguinha sim!",
    autor: "Renato Gama",
    editora: "Sá Menina",
    tema: "Autoafirmação / Negritude / Identidade",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Uma menina negra encontra força para se afirmar e se orgulhar de quem é, enfrentando o racismo com poesia.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.editorasamenina.com.br/img/neguinha-sim.jpg",
    mostruario: "/www.editorasamenina.com.br/img/neguinha-sim-150x150.jpg"
  },
  {
    id: 58,
    titulo: "Neta de Anita",
    autor: "Anderson de Oliveira",
    editora: "Maza Edições",
    tema: "História / Família / Resistência",
    genero: "Infantil / Histórico",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Garota herda a força de sua ancestral, Anita Garibaldi, e inspira coragem nas novas gerações.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2020/11/neta-de-anita.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2020/11/neta-de-anita-150x150.jpg"
  },
  {
    id: 59,
    titulo: "Nikkê",
    autor: "Édimo de Almeida Pereira",
    editora: "Maza Edições",
    tema: "Identidade / Tradição / Afeto",
    genero: "Infantil",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 32,
    resumo: "Nikkê descobre a importância de seu nome e da sua origem, mergulhando nas histórias e símbolos da cultura afro-brasileira.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2021/06/nikke.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2021/06/nikke-150x150.jpg"
  },

    {
    id: 68,
    titulo: "Pequena porta estandarte",
    autor: "Daniel Renard",
    editora: "Seed",
    tema: "Carnaval / Patrimônio / Infância",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 30,
    resumo: "Uma menina sonha em ser porta-estandarte em um desfile de carnaval, revivendo tradições culturais com beleza e esperança.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/editoraseed.com.br/img/pequena-porta.jpg",
    mostruario: "/editoraseed.com.br/img/pequena-porta-thumb.jpg"
  },
  {
    id: 69,
    titulo: "Pênalti",
    autor: "Geni Guimarães",
    editora: "Malê Mirim",
    tema: "Infância / Desigualdade / Superação",
    genero: "Infantil",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 34,
    resumo: "História de um menino negro apaixonado por futebol que enfrenta obstáculos sociais e raciais em busca de seus sonhos.",
    dataPublicacao: "2015-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.editoramale.com.br/img/penalti.jpg",
    mostruario: "/www.editoramale.com.br/img/penalti-thumb.jpg"
  },
  {
    id: 60,
    titulo: "Pequeno príncipe preto",
    autor: "Rodrigo França",
    editora: "Nova Fronteira",
    tema: "Afeto / Identidade / Protagonismo negro",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Inspirado em 'O Pequeno Príncipe', esta obra reconstrói o protagonismo de um menino negro em um universo afetivo e poético.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/novafronteira.com.br/wp-content/uploads/2021/09/pequeno-principe-preto.jpg",
    mostruario: "/novafronteira.com.br/wp-content/uploads/2021/09/pequeno-principe-preto-thumb.jpg"
  },
 
    {
    id: 61,
    titulo: "Omo-Obá: histórias de princesas",
    autor: "Kiusam de Oliveira",
    editora: "Maza Edições",
    tema: "Cultura afro-brasileira / Mitologia iorubá / Representatividade",
    genero: "Infantil / Contos",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Histórias de princesas africanas inspiradas nos orixás femininos, reforçando o empoderamento de meninas negras.",
    dataPublicacao: "2009-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/omo-oba.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/omo-oba-150x150.jpg"
  },
  {
    id: 62,
    titulo: "Omo: o rio da liberdade",
    autor: "Vanessa Alexandre",
    editora: "PAE",
    tema: "Ancestralidade / Natureza / Resistência",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Poema que narra o encontro de uma criança com o rio Omo, símbolo de força, liberdade e ancestralidade africana.",
    dataPublicacao: "2022-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/paeeditora.com.br/img/omo-rio-liberdade.jpg",
    mostruario: "/paeeditora.com.br/img/omo-rio-liberdade-thumb.jpg"
  },
  {
    id: 65,
    titulo: "O ônibus de Rosa",
    autor: "Fabrizio Silim",
    editora: "SM",
    tema: "Direitos civis / Rosa Parks / Resistência",
    genero: "Infantil / Histórico",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Baseado na história de Rosa Parks, este livro inspira coragem e resistência contra o racismo desde a infância.",
    dataPublicacao: "2008-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.smeditora.com.br/img/o-onibus-de-rosa.jpg",
    mostruario: "/www.smeditora.com.br/img/o-onibus-de-rosa-thumb.jpg"
  },
  {
    id: 66,
    titulo: "Oranyam e a grande pescaria",
    autor: "Dayse Cabral de Moura",
    editora: "Maza Edições",
    tema: "Tradições afro / Natureza / Sabedoria ancestral",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "Oranyam aprende com seu avô sobre valores ancestrais e a relação com o mar e os ciclos da vida.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/oranyam.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/oranyam-thumb.jpg"
  },
  {
    id: 67,
    titulo: "Panela de barro e colher de pau; broa de milho, berimbau e carnaval",
    autor: "Nará Souza Oliveira",
    editora: "Maza Edições",
    tema: "Saberes tradicionais / Cultura afro-brasileira / Oralidade",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 38,
    resumo: "Livro poético que celebra os utensílios, comidas e sons da cultura negra com ritmo, sabor e memória.",
    dataPublicacao: "2019-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/panela-de-barro.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/panela-de-barro-thumb.jpg"
  },

    {
    id: 68,
    titulo: "Quem contou foi Camará",
    autor: "Vários autores",
    editora: "Bejiró",
    tema: "Oralidade / Cultura africana / Sabedoria",
    genero: "Contos / Narrativas tradicionais",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 52,
    resumo: "Coletânea de histórias inspiradas na tradição oral africana, com o griot Camará como narrador.",
    dataPublicacao: "2016-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/editorabejiro.com.br/img/quem-contou-foi-camara.jpg",
    mostruario: "/editorabejiro.com.br/img/quem-contou-foi-camara-thumb.jpg"
  },
  {
    id: 69,
    titulo: "Ruas do brincar",
    autor: "Leandro Rodrigues e Fernando Erminio",
    editora: "Coleção Literária Besouro",
    tema: "Infância / Brincadeiras / Cultura popular",
    genero: "Fotolivro / Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 48,
    resumo: "Registro fotográfico e poético das brincadeiras tradicionais de rua com forte influência afro-brasileira.",
    dataPublicacao: "2020-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/colecaobesouro.com.br/img/ruas-do-brincar.jpg",
    mostruario: "/colecaobesouro.com.br/img/ruas-do-brincar-thumb.jpg"
  },
  {
    id: 70,
    titulo: "Semente que veio da África",
    autor: "Heloísa Pires Lima, Georges Gneka e Mário Lemos",
    editora: "Salamandra",
    tema: "Ancestralidade / África / Diversidade cultural",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 44,
    resumo: "Explica a influência da África no Brasil a partir da história de uma semente, símbolo da cultura viva.",
    dataPublicacao: "2007-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/salamandra.com.br/img/semente-que-veio-da-africa.jpg",
    mostruario: "/salamandra.com.br/img/semente-que-veio-da-africa-thumb.jpg"
  },

  {
    id: 71,
    titulo: "Pequenos contos negros",
    autor: "Blaise Cendrars",
    editora: "SM",
    tema: "Literatura afrodescendente / Diversidade cultural",
    genero: "Contos",
    classificacaoLiteraria: "Infantojuvenil",
    numeroPaginas: 64,
    resumo: "Antologia com histórias inspiradas em narrativas africanas e afrodescendentes, com reflexões sobre identidade e cultura.",
    dataPublicacao: "2012-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.smeditora.com.br/img/pequenos-contos-negros.jpg",
    mostruario: "/www.smeditora.com.br/img/pequenos-contos-negros-thumb.jpg"
  },
  {
    id: 72,
    titulo: "Pretinha de neve e os sete gigantes",
    autor: "Rubem Filho",
    editora: "Paulinas",
    tema: "Representatividade / Recontos afro-brasileiros",
    genero: "Conto / Releitura",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Releitura afrocentrada do clássico 'Branca de Neve', com protagonismo negro e elementos culturais brasileiros.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.paulinas.org.br/img/pretinha-de-neve.jpg",
    mostruario: "/www.paulinas.org.br/img/pretinha-de-neve-thumb.jpg"
  },
  {
    id: 73,
    titulo: "Princesa e o vento",
    autor: "Martha Rodrigues",
    editora: "Maza Edições",
    tema: "Imaginação / Ancestralidade / Natureza",
    genero: "Infantil / Poético",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "A história de uma princesa que escuta a sabedoria do vento e mergulha em uma viagem ancestral.",
    dataPublicacao: "2018-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/princesa-e-o-vento.jpg",
    mostruario: "/mazzaedicoes.com.br/wp-content/uploads/2020/03/princesa-e-o-vento-thumb.jpg"
  },
  {
    id: 74,
    titulo: "Princesas negras",
    autor: "Ariane Celestino Meireles",
    editora: "Malê Mirim",
    tema: "Autoestima / Protagonismo / Identidade",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 28,
    resumo: "Livro ilustrado que valoriza a beleza e a diversidade das meninas negras, mostrando que todas podem ser princesas.",
    dataPublicacao: "2021-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/editoramale.com.br/img/princesas-negras.jpg",
    mostruario: "/editoramale.com.br/img/princesas-negras-thumb.jpg"
  },
  {
    id: 75,
    titulo: "Quanta África tem no dia de alguém?",
    autor: "Renata Fernandes",
    editora: "Ciranda na Escola",
    tema: "África / Cotidiano / Educação",
    genero: "Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Mostra como a cultura africana está presente no cotidiano das crianças, mesmo que elas nem percebam.",
    dataPublicacao: "2021-08-01",
    dataCatalogo: "2025-06-17",
    capa: "/cirandanaescola.com.br/img/quanta-africa.jpg",
    mostruario: "/cirandanaescola.com.br/img/quanta-africa-thumb.jpg"
  },

    {
    id: 76,
    titulo: "Sonia Rosa; Tabuleiro da Baiana",
    autor: "Sonia Rosa",
    editora: "Pallas",
    tema: "Cultura / Tradições afro-brasileiras / Culinária",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Explora o universo das baianas do acarajé e suas tradições, com foco no respeito à cultura de matriz africana.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/editorapallas.com.br/img/sonia-rosa-tabuleiro.jpg",
    mostruario: "/editorapallas.com.br/img/sonia-rosa-tabuleiro-thumb.jpg"
  },
  {
    id: 77,
    titulo: "Sonia Rosa; Jongo",
    autor: "Sonia Rosa",
    editora: "Pallas",
    tema: "Música / Cultura afro-brasileira / Dança",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Apresenta o jongo, dança de origem africana presente na cultura popular brasileira, de forma acessível às crianças.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/editorapallas.com.br/img/sonia-rosa-jongo.jpg",
    mostruario: "/editorapallas.com.br/img/sonia-rosa-jongo-thumb.jpg"
  },
  {
    id: 78,
    titulo: "Sulwe",
    autor: "Lupita Nyong'o",
    editora: "Rocco Pequenos Leitores",
    tema: "Autoestima / Identidade / Cor da pele",
    genero: "Livro ilustrado / Infantil",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 48,
    resumo: "Sulwe é uma menina com a pele da cor da meia-noite que embarca em uma jornada para descobrir sua beleza interior.",
    dataPublicacao: "2020-03-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.rocco.com.br/wp-content/uploads/2020/03/sulwe.jpg",
    mostruario: "/www.rocco.com.br/wp-content/uploads/2020/03/sulwe-thumb.jpg"
  },

 {
    id: 79,
    titulo: "Sonia Rosa; Capoeira",
    autor: "Sonia Rosa",
    editora: "Pallas",
    tema: "Cultura afro-brasileira / Capoeira",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Livro introdutório sobre a capoeira, com linguagem acessível e ilustrações que retratam a importância dessa manifestação cultural.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/editorapallas.com.br/img/sonia-rosa-capoeira.jpg",
    mostruario: "/editorapallas.com.br/img/sonia-rosa-capoeira-thumb.jpg"
  },
  {
    id: 80,
    titulo: "Sonia Rosa; Maracatu",
    autor: "Sonia Rosa",
    editora: "Pallas",
    tema: "Cultura afro-brasileira / Música / Tradições",
    genero: "Infantil / Educativo",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 24,
    resumo: "Apresenta a história do maracatu e sua importância como expressão cultural afro-brasileira, em linguagem lúdica.",
    dataPublicacao: "2010-01-01",
    dataCatalogo: "2025-06-17",
    capa: "/editorapallas.com.br/img/sonia-rosa-maracatu.jpg",
    mostruario: "/editorapallas.com.br/img/sonia-rosa-maracatu-thumb.jpg"
  },

   {
    id: 81,
    titulo: "Tunde e as aves misteriosas",
    autor: "Ana Fátima",
    editora: "Ereginga Educação",
    tema: "Aventura / Mistério / Cultura africana",
    genero: "Infantil / Fantasia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 40,
    resumo: "Tunde é um menino curioso que embarca numa jornada mágica para salvar aves encantadas e redescobrir tradições ancestrais.",
    dataPublicacao: "2020-09-01",
    dataCatalogo: "2025-06-17",
    capa: "/ereginga.com.br/uploads/tunde-capa.jpg",
    mostruario: "/ereginga.com.br/uploads/tunde-thumb.jpg"
  },
  {
    id: 82,
    titulo: "Xangô, o trovão",
    autor: "Reginaldo Prandi",
    editora: "Companhia das Letrinhas",
    tema: "Mitologia africana / Religião de matriz africana / Orixás",
    genero: "Infantil / Mitologia",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 48,
    resumo: "Um retrato encantador de Xangô, o orixá do trovão e da justiça, apresentado com linguagem acessível e rica em elementos simbólicos.",
    dataPublicacao: "2001-08-01",
    dataCatalogo: "2025-06-17",
    capa: "/images.companhiadasletrinhas.com.br/xango-o-trovao.jpg",
    mostruario: "/images.companhiadasletrinhas.com.br/xango-thumb.jpg"
  },
  {
    id: 83,
    titulo: "Zula, a Guerreira",
    autor: "Marcos Cajé",
    editora: "Crianças Diversas",
    tema: "Empoderamento feminino / Cultura afro-brasileira",
    genero: "Infantil / Ação / Identidade",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 36,
    resumo: "Zula é uma heroína determinada a mudar o mundo com coragem, representando o poder das meninas negras em suas lutas e sonhos.",
    dataPublicacao: "2023-04-01",
    dataCatalogo: "2025-06-17",
    capa: "/criancasdiversas.com.br/img/zula-guerreira.jpg",
    mostruario: "/criancasdiversas.com.br/img/zula-guerreira-thumb.jpg"
  },
    {
    id: 84,
    titulo: "Super negro",
    autor: "Caio do Cordel",
    editora: "Caio do Cordel",
    tema: "Representatividade / Identidade negra / Heroísmo",
    genero: "Infantil / Aventura",
    classificacaoLiteraria: "Infantil",
    numeroPaginas: 32,
    resumo: "Uma narrativa inspiradora sobre um menino negro que descobre seu valor e poderes ao enfrentar desafios cotidianos como um verdadeiro herói.",
    dataPublicacao: "2021-06-01",
    dataCatalogo: "2025-06-17",
    capa: "/www.caiodocordel.com.br/images/super-negro.jpg",
    mostruario: "/www.caiodocordel.com.br/images/super-negro-thumb.jpg"
  },
 

];

 // Cabeçalhos CORS padrão
    const corsHeaders = {
  "Access-Control-Allow-Origin": "*", // ou "http://localhost:3000"
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type", // CORRIGIDO
  "Content-Type": "application/json",
};


    // OPTIONS (preflight)
    if (method === "OPTIONS") {
      return new Response(null, {
        status: 204,
        headers: corsHeaders,
      });
    }

    // Rota: /livros/:id
    const matchId = pathname.match(/^\/livros\/(\d+)$/);
    if (matchId) {
      const id = parseInt(matchId[1]);
      const livro = livros.find((l) => l.id === id);

      if (livro) {
        return new Response(JSON.stringify(livro), {
          status: 200,
          headers: corsHeaders,
        });
      } else {
        return new Response(JSON.stringify({ erro: "Livro não encontrado" }), {
          status: 404,
          headers: corsHeaders,
        });
      }
    }

    // Rota: /livros (lista completa)
    if (pathname === "/livros") {
      return new Response(JSON.stringify(livros), {
        status: 200,
        headers: corsHeaders,
      });
    }

    // Rota não encontrada
    return new Response(JSON.stringify({ erro: "Rota não encontrada" }), {
      status: 404,
      headers: corsHeaders,
    });
  },
};