INSERT INTO livros (
  titulo,
  autor,
  editora,
  tema,
  genero,
  classificacaoLiteraria,
  numeroPaginas,
  resumo,
  dataPublicacao,
  dataCatalogo,
  capa,
  mostruario
) VALUES
(
   'Tebas Joaquim Pinto de Oliveira',
   'Orlando Nilha',
   'Mostarda',
   'Coleção Black Power',
   'Infantil',
   'Infantil',
   32,
   'Biografia infantil de Tebas, arquiteto negro que deixou marcas na paisagem urbana de São Paulo colonial.',
   '2021-03-01',
   '2025-07-30',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/TebasJoaquimPintoDeOliveira.jpeg?raw=true',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/TebasJoaquimPintoDeOliveira.jpeg?raw=true'
),
(
   'Madalena Paraguaçu',
   'Orlando Nilha',
   'Mostarda',
   'Coleção Black Power',
   'Biografia infantojuvenil',
   'Infantojuvenil',
   32,
   'Narra a vida de Madalena Paraguaçu, líder indígena tupi e primeira brasileira alfabetizada, que defendeu a educação e os direitos dos povos indígenas durante o período colonial.',
   '2023-01-01',
   '2025-07-15',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Paraguacu.jpeg?raw=true',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Paraguacu.jpeg?raw=true'
),
(
   'André e Antônio Rebouças',
   'Júlio Emílio Braz',
   'Mostarda',
   'Coleção Black Power',
   'Biografia infantojuvenil',
   'Infantojuvenil',
   32,
   'História dos irmãos Rebouças, primeiros homens negros a se tornarem engenheiros no Brasil, destacando sua formação e contribuição para obras como a ferrovia Paranaguá‑Curitiba, e sua atuação contra o racismo.',
   '2022-01-01',
   '2025-07-15',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Andre.jpeg?raw=true',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Andre.jpeg?raw=true'
),
(
   'Barack Obama',
   'Orlando Nilha',
   'Mostarda',
   'Coleção Black Power',
   'Biografia infantojuvenil',
   'Infantojuvenil',
   32,
   'Trajetória de Barack Obama como o primeiro presidente negro dos Estados Unidos, sua atuação baseada na diplomacia, defesa dos direitos LGBT e protagonismo global como símbolo de esperança e representatividade.',
   '2023-01-01',
   '2025-07-15',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Obama.jpeg?raw=true',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Obama.jpeg?raw=true'
),
(
   'Rosa Parks',
   'Orlando Nilha',
   'Mostarda',
   'Coleção Black Power',
   'Biografia infantojuvenil',
   'Infantojuvenil',
   32,
   'Conta a história de Rosa Parks, que desafiou a segregação ao recusar-se a ceder seu lugar no ônibus nos EUA, dando início a um movimento de massa pela igualdade racial e direitos civis.',
   '2022-01-01',
   '2025-07-15',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Rosa.jpeg?raw=true',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Rosa.jpeg?raw=true'
),
(
   'Sueli Carneiro',
   'Orlando Nilha',
   'Mostarda',
   'Coleção Black Power',
   'Biografia infantojuvenil',
   'Infantojuvenil',
   32,
   'Retrata Sueli Carneiro, escritora e filósofa brasileira que lutou por igualdade étnico-racial e de gênero, fundadora do Geledés – Instituto da Mulher Negra e articuladora das cotas e representatividade da mulher negra.',
   '2023-01-01',
   '2025-07-15',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/capa/Sueli.jpeg?raw=true',
   'https://github.com/Arthurbhs/Biblioteca_APP/blob/main/assets/images/thumbnaill/Sueli.jpeg?raw=true'
);
